service: username-detector
provider:
  name: aws
  runtime: nodejs12.x
functions:
  run:
    handler: bot.run
    events:
      # - schedule: rate(30 seconds)
      - http:
          path: users/create
          method: get
